### ISSUE TITLE
Using the library with Sveltekit - Cannot read properties of undefined (reading 'from')

### ISSUE THREAD

**Issue by timoconnor** [TobiasNickel/tXml#48]
I am just really learning Sevelte and Javascript webdevelopment - I am having issues using the library.

I have done:
npm i txml

But I am not sure how to 'import' it.  I have tried:
import * as txml from 'txml';

But that gives me a 500 error and the message:
TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:11:12)
    at __require2 (chunk-OZI5HTJH.js?v=5487c821:15:50)
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:55:14)
    at __require2 (chunk-OZI5HTJH.js?v=5487c821:15:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require2 (chunk-OZI5HTJH.js?v=5487c821:15:50)
    at node_modules/through2/through2.js (through2.js:1:17)
    at __require2 (chunk-OZI5HTJH.js?v=5487c821:15:50)
    at transformStream.mjs:2:22

**Comment by TobiasNickel** [comment]
thanks for reporting this, I think it is time that this lib should be lifted to a js module and leave cmd behind. to support new and modern projects.
